#!/bin/bash

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

echo 'changed files: \n';
echo $changed_files;

# `npm install` and `npm prune` if the `package.json` file gets changed
# to update all the nodejs ( grunt ) dependencies deleting the unused packages (not listed into the  `package.json` file)
check_run package.json "npm install && npm prune"

# `bower install` and `bower prune` if the `bower.json` file gets changed
# to install all the frontend dependencies removing the unused packages ( not listed into the  `bower.json` file )
check_run bower.json "bower install && bower prune"

# `compass compile` to compil all the scss files when they get changed
check_run .scss "compass compile"
